name: GitHub Snake

on:
  workflow_dispatch:  # تشغيل يدوي لأول مرة
  schedule:
    - cron: '0 0 * * *'  # تحديث يومي UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate GitHub Snake
        uses: Ileriayo/github-contribution-grid-snake@v2
        with:
          username: moustafaibrahim10
          output: ./output/github-contribution-grid-snake.svg
      - name: Commit Snake SVG
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./output/github-contribution-grid-snake.svg
          git commit -m "Update Snake contribution graph" || echo "No changes to commit"
          git push
